/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GrievanceContractOptimized {
  export type ComplaintStruct = {
    complainantIdHash: BytesLike;
    descriptionHash: BytesLike;
    attachmentHash: BytesLike;
    locationHash: BytesLike;
    submissionDate: BigNumberish;
    lastUpdated: BigNumberish;
    upvoteCount: BigNumberish;
    urgencyLevel: BigNumberish;
    statusCode: BigNumberish;
    isPublic: boolean;
  };

  export type ComplaintStructOutput = [
    complainantIdHash: string,
    descriptionHash: string,
    attachmentHash: string,
    locationHash: string,
    submissionDate: bigint,
    lastUpdated: bigint,
    upvoteCount: bigint,
    urgencyLevel: bigint,
    statusCode: bigint,
    isPublic: boolean
  ] & {
    complainantIdHash: string;
    descriptionHash: string;
    attachmentHash: string;
    locationHash: string;
    submissionDate: bigint;
    lastUpdated: bigint;
    upvoteCount: bigint;
    urgencyLevel: bigint;
    statusCode: bigint;
    isPublic: boolean;
  };

  export type UserStruct = {
    emailHash: BytesLike;
    aadhaarHash: BytesLike;
    locationHash: BytesLike;
    registrationDate: BigNumberish;
    isActive: boolean;
  };

  export type UserStructOutput = [
    emailHash: string,
    aadhaarHash: string,
    locationHash: string,
    registrationDate: bigint,
    isActive: boolean
  ] & {
    emailHash: string;
    aadhaarHash: string;
    locationHash: string;
    registrationDate: bigint;
    isActive: boolean;
  };
}

export interface GrievanceContractOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignComplaint"
      | "checkComplaintExists"
      | "checkUserExists"
      | "complaintExists"
      | "complaints"
      | "createAuditLog"
      | "getComplaint"
      | "getCounts"
      | "getUser"
      | "registerComplaint"
      | "registerUser"
      | "resolveComplaint"
      | "totalAuditLogs"
      | "totalComplaints"
      | "totalUsers"
      | "updateComplaintStatus"
      | "updateUpvoteCount"
      | "userExists"
      | "users"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditLogCreated"
      | "ComplaintAssigned"
      | "ComplaintLocationStored"
      | "ComplaintRegistered"
      | "ComplaintResolved"
      | "ComplaintStatusUpdated"
      | "UpvoteAdded"
      | "UserLocationStored"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignComplaint",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkComplaintExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUserExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "complaintExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "complaints",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuditLog",
    values: [string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaint",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getCounts", values?: undefined): string;
  encodeFunctionData(functionFragment: "getUser", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerComplaint",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      boolean,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [
      string,
      string,
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveComplaint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAuditLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalComplaints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateComplaintStatus",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUpvoteCount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkComplaintExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUserExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complaintExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "complaints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAuditLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAuditLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalComplaints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateComplaintStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUpvoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace AuditLogCreatedEvent {
  export type InputTuple = [
    logId: string,
    action: string,
    userId: string,
    complaintId: string,
    details: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    logId: string,
    action: string,
    userId: string,
    complaintId: string,
    details: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    logId: string;
    action: string;
    userId: string;
    complaintId: string;
    details: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintAssignedEvent {
  export type InputTuple = [
    complaintId: string,
    assignedTo: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    assignedTo: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    assignedTo: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintLocationStoredEvent {
  export type InputTuple = [
    complaintId: string,
    pin: string,
    district: string,
    city: string,
    locality: string,
    state: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    pin: string,
    district: string,
    city: string,
    locality: string,
    state: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    pin: string;
    district: string;
    city: string;
    locality: string;
    state: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintRegisteredEvent {
  export type InputTuple = [
    complaintId: string,
    complainantId: string,
    categoryId: string,
    subCategory: string,
    department: string,
    urgency: BigNumberish,
    descriptionHash: BytesLike,
    attachmentHash: BytesLike,
    locationHash: BytesLike,
    isPublic: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    complainantId: string,
    categoryId: string,
    subCategory: string,
    department: string,
    urgency: bigint,
    descriptionHash: string,
    attachmentHash: string,
    locationHash: string,
    isPublic: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    complainantId: string;
    categoryId: string;
    subCategory: string;
    department: string;
    urgency: bigint;
    descriptionHash: string;
    attachmentHash: string;
    locationHash: string;
    isPublic: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintResolvedEvent {
  export type InputTuple = [complaintId: string, timestamp: BigNumberish];
  export type OutputTuple = [complaintId: string, timestamp: bigint];
  export interface OutputObject {
    complaintId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintStatusUpdatedEvent {
  export type InputTuple = [
    complaintId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    statusName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    oldStatus: bigint,
    newStatus: bigint,
    statusName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    oldStatus: bigint;
    newStatus: bigint;
    statusName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpvoteAddedEvent {
  export type InputTuple = [
    complaintId: string,
    newCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    newCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    newCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserLocationStoredEvent {
  export type InputTuple = [
    userId: string,
    pin: string,
    district: string,
    city: string,
    state: string,
    municipal: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userId: string,
    pin: string,
    district: string,
    city: string,
    state: string,
    municipal: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userId: string;
    pin: string;
    district: string;
    city: string;
    state: string;
    municipal: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    userId: string,
    name: string,
    role: string,
    emailHash: BytesLike,
    aadhaarHash: BytesLike,
    locationHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userId: string,
    name: string,
    role: string,
    emailHash: string,
    aadhaarHash: string,
    locationHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userId: string;
    name: string;
    role: string;
    emailHash: string;
    aadhaarHash: string;
    locationHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GrievanceContractOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): GrievanceContractOptimized;
  waitForDeployment(): Promise<this>;

  interface: GrievanceContractOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignComplaint: TypedContractMethod<
    [_complaintId: string, _assignedTo: string],
    [void],
    "nonpayable"
  >;

  checkComplaintExists: TypedContractMethod<
    [_complaintId: string],
    [boolean],
    "view"
  >;

  checkUserExists: TypedContractMethod<[_userId: string], [boolean], "view">;

  complaintExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  complaints: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        complainantIdHash: string;
        descriptionHash: string;
        attachmentHash: string;
        locationHash: string;
        submissionDate: bigint;
        lastUpdated: bigint;
        upvoteCount: bigint;
        urgencyLevel: bigint;
        statusCode: bigint;
        isPublic: boolean;
      }
    ],
    "view"
  >;

  createAuditLog: TypedContractMethod<
    [
      _logId: string,
      _action: string,
      _userId: string,
      _complaintId: string,
      _details: string
    ],
    [void],
    "nonpayable"
  >;

  getComplaint: TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.ComplaintStructOutput],
    "view"
  >;

  getCounts: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        userCount: bigint;
        complaintCount: bigint;
        auditLogCount: bigint;
      }
    ],
    "view"
  >;

  getUser: TypedContractMethod<
    [_userId: string],
    [GrievanceContractOptimized.UserStructOutput],
    "view"
  >;

  registerComplaint: TypedContractMethod<
    [
      _complaintId: string,
      _complainantId: string,
      _categoryId: string,
      _subCategory: string,
      _department: string,
      _urgency: BigNumberish,
      _descriptionHash: BytesLike,
      _attachmentHash: BytesLike,
      _locationHash: BytesLike,
      _isPublic: boolean,
      _pin: string,
      _district: string,
      _city: string,
      _locality: string,
      _state: string
    ],
    [void],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [
      _userId: string,
      _name: string,
      _role: string,
      _emailHash: BytesLike,
      _aadhaarHash: BytesLike,
      _locationHash: BytesLike,
      _pin: string,
      _district: string,
      _city: string,
      _state: string,
      _municipal: string
    ],
    [void],
    "nonpayable"
  >;

  resolveComplaint: TypedContractMethod<
    [_complaintId: string],
    [void],
    "nonpayable"
  >;

  totalAuditLogs: TypedContractMethod<[], [bigint], "view">;

  totalComplaints: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  updateComplaintStatus: TypedContractMethod<
    [_complaintId: string, _newStatus: BigNumberish, _statusName: string],
    [void],
    "nonpayable"
  >;

  updateUpvoteCount: TypedContractMethod<
    [_complaintId: string, _newCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  userExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  users: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        emailHash: string;
        aadhaarHash: string;
        locationHash: string;
        registrationDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  verifyHash: TypedContractMethod<
    [_complaintId: string, _descriptionHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignComplaint"
  ): TypedContractMethod<
    [_complaintId: string, _assignedTo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkComplaintExists"
  ): TypedContractMethod<[_complaintId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkUserExists"
  ): TypedContractMethod<[_userId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "complaintExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "complaints"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        complainantIdHash: string;
        descriptionHash: string;
        attachmentHash: string;
        locationHash: string;
        submissionDate: bigint;
        lastUpdated: bigint;
        upvoteCount: bigint;
        urgencyLevel: bigint;
        statusCode: bigint;
        isPublic: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAuditLog"
  ): TypedContractMethod<
    [
      _logId: string,
      _action: string,
      _userId: string,
      _complaintId: string,
      _details: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getComplaint"
  ): TypedContractMethod<
    [_complaintId: string],
    [GrievanceContractOptimized.ComplaintStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCounts"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        userCount: bigint;
        complaintCount: bigint;
        auditLogCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_userId: string],
    [GrievanceContractOptimized.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerComplaint"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _complainantId: string,
      _categoryId: string,
      _subCategory: string,
      _department: string,
      _urgency: BigNumberish,
      _descriptionHash: BytesLike,
      _attachmentHash: BytesLike,
      _locationHash: BytesLike,
      _isPublic: boolean,
      _pin: string,
      _district: string,
      _city: string,
      _locality: string,
      _state: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [
      _userId: string,
      _name: string,
      _role: string,
      _emailHash: BytesLike,
      _aadhaarHash: BytesLike,
      _locationHash: BytesLike,
      _pin: string,
      _district: string,
      _city: string,
      _state: string,
      _municipal: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveComplaint"
  ): TypedContractMethod<[_complaintId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAuditLogs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalComplaints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateComplaintStatus"
  ): TypedContractMethod<
    [_complaintId: string, _newStatus: BigNumberish, _statusName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUpvoteCount"
  ): TypedContractMethod<
    [_complaintId: string, _newCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        emailHash: string;
        aadhaarHash: string;
        locationHash: string;
        registrationDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [_complaintId: string, _descriptionHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuditLogCreated"
  ): TypedContractEvent<
    AuditLogCreatedEvent.InputTuple,
    AuditLogCreatedEvent.OutputTuple,
    AuditLogCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintAssigned"
  ): TypedContractEvent<
    ComplaintAssignedEvent.InputTuple,
    ComplaintAssignedEvent.OutputTuple,
    ComplaintAssignedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintLocationStored"
  ): TypedContractEvent<
    ComplaintLocationStoredEvent.InputTuple,
    ComplaintLocationStoredEvent.OutputTuple,
    ComplaintLocationStoredEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintRegistered"
  ): TypedContractEvent<
    ComplaintRegisteredEvent.InputTuple,
    ComplaintRegisteredEvent.OutputTuple,
    ComplaintRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintResolved"
  ): TypedContractEvent<
    ComplaintResolvedEvent.InputTuple,
    ComplaintResolvedEvent.OutputTuple,
    ComplaintResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintStatusUpdated"
  ): TypedContractEvent<
    ComplaintStatusUpdatedEvent.InputTuple,
    ComplaintStatusUpdatedEvent.OutputTuple,
    ComplaintStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UpvoteAdded"
  ): TypedContractEvent<
    UpvoteAddedEvent.InputTuple,
    UpvoteAddedEvent.OutputTuple,
    UpvoteAddedEvent.OutputObject
  >;
  getEvent(
    key: "UserLocationStored"
  ): TypedContractEvent<
    UserLocationStoredEvent.InputTuple,
    UserLocationStoredEvent.OutputTuple,
    UserLocationStoredEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "AuditLogCreated(string,string,string,string,string,uint256)": TypedContractEvent<
      AuditLogCreatedEvent.InputTuple,
      AuditLogCreatedEvent.OutputTuple,
      AuditLogCreatedEvent.OutputObject
    >;
    AuditLogCreated: TypedContractEvent<
      AuditLogCreatedEvent.InputTuple,
      AuditLogCreatedEvent.OutputTuple,
      AuditLogCreatedEvent.OutputObject
    >;

    "ComplaintAssigned(string,string,uint256)": TypedContractEvent<
      ComplaintAssignedEvent.InputTuple,
      ComplaintAssignedEvent.OutputTuple,
      ComplaintAssignedEvent.OutputObject
    >;
    ComplaintAssigned: TypedContractEvent<
      ComplaintAssignedEvent.InputTuple,
      ComplaintAssignedEvent.OutputTuple,
      ComplaintAssignedEvent.OutputObject
    >;

    "ComplaintLocationStored(string,string,string,string,string,string,uint256)": TypedContractEvent<
      ComplaintLocationStoredEvent.InputTuple,
      ComplaintLocationStoredEvent.OutputTuple,
      ComplaintLocationStoredEvent.OutputObject
    >;
    ComplaintLocationStored: TypedContractEvent<
      ComplaintLocationStoredEvent.InputTuple,
      ComplaintLocationStoredEvent.OutputTuple,
      ComplaintLocationStoredEvent.OutputObject
    >;

    "ComplaintRegistered(string,string,string,string,string,uint8,bytes32,bytes32,bytes32,bool,uint256)": TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;
    ComplaintRegistered: TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;

    "ComplaintResolved(string,uint256)": TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;
    ComplaintResolved: TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;

    "ComplaintStatusUpdated(string,uint8,uint8,string,uint256)": TypedContractEvent<
      ComplaintStatusUpdatedEvent.InputTuple,
      ComplaintStatusUpdatedEvent.OutputTuple,
      ComplaintStatusUpdatedEvent.OutputObject
    >;
    ComplaintStatusUpdated: TypedContractEvent<
      ComplaintStatusUpdatedEvent.InputTuple,
      ComplaintStatusUpdatedEvent.OutputTuple,
      ComplaintStatusUpdatedEvent.OutputObject
    >;

    "UpvoteAdded(string,uint32,uint256)": TypedContractEvent<
      UpvoteAddedEvent.InputTuple,
      UpvoteAddedEvent.OutputTuple,
      UpvoteAddedEvent.OutputObject
    >;
    UpvoteAdded: TypedContractEvent<
      UpvoteAddedEvent.InputTuple,
      UpvoteAddedEvent.OutputTuple,
      UpvoteAddedEvent.OutputObject
    >;

    "UserLocationStored(string,string,string,string,string,string,uint256)": TypedContractEvent<
      UserLocationStoredEvent.InputTuple,
      UserLocationStoredEvent.OutputTuple,
      UserLocationStoredEvent.OutputObject
    >;
    UserLocationStored: TypedContractEvent<
      UserLocationStoredEvent.InputTuple,
      UserLocationStoredEvent.OutputTuple,
      UserLocationStoredEvent.OutputObject
    >;

    "UserRegistered(string,string,string,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
