/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GrievanceContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignComplaint"
      | "complaintExists"
      | "complaintIds"
      | "complaints"
      | "getComplaint"
      | "getComplaintCount"
      | "getComplaintIdByIndex"
      | "registerComplaint"
      | "resolveComplaint"
      | "updateStatus"
      | "verifyComplaintHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplaintAssigned"
      | "ComplaintRegistered"
      | "ComplaintResolved"
      | "ComplaintStatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignComplaint",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "complaintExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "complaintIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "complaints", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getComplaint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaintCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getComplaintIdByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerComplaint",
    values: [string, string, string, string, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveComplaint",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyComplaintHash",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complaintExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complaintIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "complaints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaintCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplaintIdByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveComplaint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyComplaintHash",
    data: BytesLike
  ): Result;
}

export namespace ComplaintAssignedEvent {
  export type InputTuple = [
    complaintId: string,
    assignedTo: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    assignedTo: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    assignedTo: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintRegisteredEvent {
  export type InputTuple = [
    complaintId: string,
    category: string,
    urgency: string,
    submittedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    category: string,
    urgency: string,
    submittedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    category: string;
    urgency: string;
    submittedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintResolvedEvent {
  export type InputTuple = [
    complaintId: string,
    resolutionDate: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    resolutionDate: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    resolutionDate: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplaintStatusUpdatedEvent {
  export type InputTuple = [
    complaintId: string,
    newStatus: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    complaintId: string,
    newStatus: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    complaintId: string;
    newStatus: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GrievanceContract extends BaseContract {
  connect(runner?: ContractRunner | null): GrievanceContract;
  waitForDeployment(): Promise<this>;

  interface: GrievanceContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignComplaint: TypedContractMethod<
    [_complaintId: string, _assignedTo: string],
    [void],
    "nonpayable"
  >;

  complaintExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  complaintIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  complaints: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        complaintId: string;
        category: string;
        subcategory: string;
        urgency: string;
        status: string;
        descriptionHash: string;
        attachmentHash: string;
        submittedBy: string;
        timestamp: bigint;
        lastUpdated: bigint;
        assignedTo: string;
        resolutionDate: string;
      }
    ],
    "view"
  >;

  getComplaint: TypedContractMethod<
    [_complaintId: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        complaintId: string;
        category: string;
        subcategory: string;
        urgency: string;
        status: string;
        descriptionHash: string;
        attachmentHash: string;
        submittedBy: string;
        timestamp: bigint;
        lastUpdated: bigint;
        assignedTo: string;
        resolutionDate: string;
      }
    ],
    "view"
  >;

  getComplaintCount: TypedContractMethod<[], [bigint], "view">;

  getComplaintIdByIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  registerComplaint: TypedContractMethod<
    [
      _complaintId: string,
      _category: string,
      _subcategory: string,
      _urgency: string,
      _descriptionHash: string,
      _attachmentHash: string,
      _submittedBy: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  resolveComplaint: TypedContractMethod<
    [_complaintId: string, _resolutionDate: string],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [_complaintId: string, _newStatus: string],
    [void],
    "nonpayable"
  >;

  verifyComplaintHash: TypedContractMethod<
    [_complaintId: string, _descriptionHash: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignComplaint"
  ): TypedContractMethod<
    [_complaintId: string, _assignedTo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "complaintExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "complaintIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "complaints"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        complaintId: string;
        category: string;
        subcategory: string;
        urgency: string;
        status: string;
        descriptionHash: string;
        attachmentHash: string;
        submittedBy: string;
        timestamp: bigint;
        lastUpdated: bigint;
        assignedTo: string;
        resolutionDate: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComplaint"
  ): TypedContractMethod<
    [_complaintId: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        complaintId: string;
        category: string;
        subcategory: string;
        urgency: string;
        status: string;
        descriptionHash: string;
        attachmentHash: string;
        submittedBy: string;
        timestamp: bigint;
        lastUpdated: bigint;
        assignedTo: string;
        resolutionDate: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComplaintCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getComplaintIdByIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerComplaint"
  ): TypedContractMethod<
    [
      _complaintId: string,
      _category: string,
      _subcategory: string,
      _urgency: string,
      _descriptionHash: string,
      _attachmentHash: string,
      _submittedBy: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveComplaint"
  ): TypedContractMethod<
    [_complaintId: string, _resolutionDate: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [_complaintId: string, _newStatus: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyComplaintHash"
  ): TypedContractMethod<
    [_complaintId: string, _descriptionHash: string],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ComplaintAssigned"
  ): TypedContractEvent<
    ComplaintAssignedEvent.InputTuple,
    ComplaintAssignedEvent.OutputTuple,
    ComplaintAssignedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintRegistered"
  ): TypedContractEvent<
    ComplaintRegisteredEvent.InputTuple,
    ComplaintRegisteredEvent.OutputTuple,
    ComplaintRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintResolved"
  ): TypedContractEvent<
    ComplaintResolvedEvent.InputTuple,
    ComplaintResolvedEvent.OutputTuple,
    ComplaintResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ComplaintStatusUpdated"
  ): TypedContractEvent<
    ComplaintStatusUpdatedEvent.InputTuple,
    ComplaintStatusUpdatedEvent.OutputTuple,
    ComplaintStatusUpdatedEvent.OutputObject
  >;

  filters: {
    "ComplaintAssigned(string,string,uint256)": TypedContractEvent<
      ComplaintAssignedEvent.InputTuple,
      ComplaintAssignedEvent.OutputTuple,
      ComplaintAssignedEvent.OutputObject
    >;
    ComplaintAssigned: TypedContractEvent<
      ComplaintAssignedEvent.InputTuple,
      ComplaintAssignedEvent.OutputTuple,
      ComplaintAssignedEvent.OutputObject
    >;

    "ComplaintRegistered(string,string,string,address,uint256)": TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;
    ComplaintRegistered: TypedContractEvent<
      ComplaintRegisteredEvent.InputTuple,
      ComplaintRegisteredEvent.OutputTuple,
      ComplaintRegisteredEvent.OutputObject
    >;

    "ComplaintResolved(string,string,uint256)": TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;
    ComplaintResolved: TypedContractEvent<
      ComplaintResolvedEvent.InputTuple,
      ComplaintResolvedEvent.OutputTuple,
      ComplaintResolvedEvent.OutputObject
    >;

    "ComplaintStatusUpdated(string,string,uint256)": TypedContractEvent<
      ComplaintStatusUpdatedEvent.InputTuple,
      ComplaintStatusUpdatedEvent.OutputTuple,
      ComplaintStatusUpdatedEvent.OutputObject
    >;
    ComplaintStatusUpdated: TypedContractEvent<
      ComplaintStatusUpdatedEvent.InputTuple,
      ComplaintStatusUpdatedEvent.OutputTuple,
      ComplaintStatusUpdatedEvent.OutputObject
    >;
  };
}
