/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GrievanceContractOptimized } from "./GrievanceContractOptimized";
export * as factories from "./factories";
export { GrievanceContractOptimized__factory } from "./factories/GrievanceContractOptimized__factory";
